# Root logger
log4j.rootLogger=INFO, stdout

# Logger infos
log4j.logger.org.apache.geronimo.gshell.remote=WARN

# CONSOLE appender not used by default
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ABSOLUTE} | %-5.5p | %-16.16t | %-32.32c{1} | %-32.32C %4L | %m%n

# File appender
log4j.appender.out=org.apache.log4j.FileAppender
log4j.appender.out.layout=org.apache.log4j.PatternLayout
log4j.appender.out.layout.ConversionPattern=%d{ABSOLUTE} | %-5.5p | %-16.16t | %-32.32c{1} | %-32.32C %4L | %m%n
log4j.appender.out.file=${servicemix.base}/data/log/servicemix.log
log4j.appender.out.append=true

#log4j.logger.org.apache.cxf=DEBUG
log4j.logger.com.fusesource=DEBUG