
package com.fusesource.training.helloworld;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Progress FUSE Services Framework 2.2.9-fuse-01-00
 * Wed Aug 25 15:03:35 EDT 2010
 * Generated source version: 2.2.9-fuse-01-00
 * 
 */

public final class HelloWorld_SOAPOverHTTPEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://fusesource.com/training/HelloWorld", "HelloWorldService");

    private HelloWorld_SOAPOverHTTPEndpoint_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HelloWorldService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWorldService ss = new HelloWorldService(wsdlURL, SERVICE_NAME);
        HelloWorld port = ss.getSOAPOverHTTPEndpoint();  
        
        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_message = "";
        java.lang.String _sayHello__return = port.sayHello(_sayHello_message);
        System.out.println("sayHello.result=" + _sayHello__return);


        }

        System.exit(0);
    }

}
